name: CICD

on:
  create:
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: install deps
      run: npm ci --no-optional
    - name: run tests
      run: npm run test:single-run
  deploy:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v2
    - uses: digitalocean/action-doctl@master      
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      with:
        args: compute ssh egg-party-droplet
    - name: remote - install deps
      run: npm ci --no-optional
    - name: remote - run tests
      run: npm run test:single-run
    - name: remote - restart app
      run: pm2 restart all
      continue-on-error: true
