name: Deploy to Production

on:
  push:
    branches: [master]

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v2
    - uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: deploy prod
      run: npx pm2 deploy production
